### ISSUE TITLE
TypeORM not loading correct settings

### ISSUE THREAD

**Issue by isiah-lloyd** [nestjs-community/nestjs-config#101]
**Issue type:**

- [ x  ] question
- [ ] bug report
- [ ] feature request
- [ ] documentation issue

**nestjs-config version**

1.4.0

**@nestjs/common+core or other package versions**
 - @nestjs/common:   6.2.4
 - @nestjs/core: 6.2.4
- @nestjs/typeorm: 6.1.1
#### Excepted behavior 

The database would connect successfully using my settings in `database.ts`

#### Actual behavior or outcome (for issue):

TypeORM tries to connect to my unix usernames database, which I'm assuming is the default behavior when TypeORM is not passed any configuration settings. 

#### Replication/Example

app.module.ts:
```ts
import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { UserModule } from './user/user.module';

import { ConfigModule, ConfigService} from 'nestjs-config';
import * as path from 'path';
import { TypeOrmModule } from '@nestjs/typeorm';

@Module({
  imports: [UserModule, ConfigModule,
    ConfigModule.load(path.resolve(__dirname, 'config', '**/!(*.d).{ts,js}')),
    TypeOrmModule.forRootAsync({
      useFactory: (config: ConfigService) => config.get('database'),
      inject: [ConfigService],
  })],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {
  constructor(config: ConfigService) {
    console.log(config.get('database'));
  }

}
```
database.ts
```ts
export default {
    type: 'postgres',
    host: process.env.TYPEORM_HOST,
    username: process.env.TYPEORM_USERNAME,
    password: process.env.TYPEORM_PASSWORD,
    name: process.env.TYPEORM_DATABASE,
    port: parseInt(process.env.TYPEORM_PORT, 10),
    logging: process.env.TYPEORM_LOGGING === 'true',
    entities: [
        __dirname + '/../**/*.entity{.ts,.js}',
    ],
    synchronize: process.env.production !== 'true',
};
```
Note the `console.log(config.get('database'));`, which does correctly output the configuration object. 
```

**Comment by isiah-lloyd** [comment]
I'm dumb, `name` just needed to be changed to `database` in `database.ts`

**Comment by bashleigh** [comment]
Sorry. I'm the idiot. I put name in the readme...

**Comment by isiah-lloyd** [comment]
Hah! I guess that's where I got it from :)

**Comment by bashleigh** [comment]
My bad!! 😂😂

**Comment by bashleigh** [comment]
@isiah-lloyd fixed 👍 thanks for making an issue!!
