### ISSUE TITLE
Add decorator to inject a single parameter

### ISSUE THREAD

**Issue by regniblod** [nestjs-community/nestjs-config#12]
Injecting the whole `ConfigService` seems a bit overkill if only one parameter is needed (and also not a good practice).

Would it be possible to create a decorator to inject only one parameter? Something like `@InjectConfigParam('port')`

**Comment by bashleigh** [comment]
I've been experimenting with decorators with my end goal being something similar to this. However my knowledge of the nestjs container is quite slim at the moment. I've attempted something similar however I've not really developed anything worthy of PR-ing. 

I will attempt to do this without requiring to inject the config service into the class however at the moment I'm not sure it's 100% possible.

**Comment by bashleigh** [comment]
#9

**Comment by bashleigh** [comment]
This has been added by @shekohex and is now on master, https://github.com/nestjs-community/nestjs-config#decorators I'll release this shortly.

**Comment by bashleigh** [comment]
this has now been published as v1.2.1
