### ISSUE TITLE
Question: What is a way to use dotenv-safe?

### ISSUE THREAD

**Issue by andrew-yustyk** [nestjs-community/nestjs-config#18]
[dotenv-safe](https://www.npmjs.com/package/dotenv-safe) ensures that all necessary environment variables are defined after reading from .env.

Is it possible to extend ConfigModule and/or ConfigService for using dotenv-safe?

**Comment by fenos** [comment]
Hi @andrew-yustyk 

Thanks for the suggestion. 

You are welcome to make a PR if you can. 

I'd be happy to have this functionality optional driven by a `safe` flag upon initialisation of the `ConfigModule` something like: `ConfigModule.load({safe: true})`

By default, I would keep it false.

From the documentation of `dotenv-safe` looks, that we can use the flag `allowEmptyValues` to turn `on` or `off` the guard.

https://www.npmjs.com/package/dotenv-safe#options

**Comment by andrew-yustyk** [comment]
I'm agree with you, that `safe` option should be optional and disabled bu default.

As for the `allowEmptyValues` from `dotenv-safe`, it was creating for the another purposes as far as I understand. Whet `allowEmptyValues` option is `true`, `dotenv-save` allows to define env vars with empty values:
```
MY_VARIABLE=
``` 

but variable still needs to be present even with empty value. In a case when required variable doesn't exist in process.env, an error still will be thrown.

I think will be better to add additional options for `dotenv-safe` to the `ConfigModule.load()` method

**Comment by andrew-yustyk** [comment]
I'll try to make a PR in the near time
