### ISSUE TITLE
Resolve bad config name because of file separator

### ISSUE THREAD

**Issue by Kapcash** [nestjs-community/nestjs-config#28]
Hey there!

I was trying for the first time your very good looking library but I could not get it working on my setup.
I digged a bit to find out what's the problem and it seems that the **last '_node-glob_' version is breaking some things on Windows.**

**When resolving configuration files, it transforms the backslashes into forward slashes**, look at this code : https://github.com/isaacs/node-glob/blob/master/common.js#L104

So Nest-config get some path like '_C:/Users/Me/project/production_', and uses the `path.sep` method to split it ([here](https://github.com/nestjs-community/nestjs-config/blob/master/src/module/config.service.ts#L259)). But, on Windows, the `path.sep` obviously resolves with a backslash '\\', so it doesn't split anything here.
Then we have bad configuration names with the full file path instead of the file name, so everything gets 'undefined' when trying to get some values!

I don't know if it's a _glob_ issue or a _Nest-config_ one. I could prepare a workaround if needed :)
Let me know!

**Comment by Kapcash** [comment]
Ok, just found out that this glob behaviour is expected (See [this thread](https://github.com/isaacs/node-glob/pull/263))
So I'm going to work on a small fix for nest-config :)

**Comment by Kapcash** [comment]
Sure, thanks for merging the changes!

**Comment by bashleigh** [comment]
published v1.2.4 👍
