### ISSUE TITLE
Can not inject config param in constructor

### ISSUE THREAD

**Issue by regniblod** [nestjs-community/nestjs-config#30]
When I try to inject a param in the constructor of my class using the `ConfigParam` decorator on the function argument and the `Configurable` decorator in the function, as suggested by the docs, TypeScript is throwing an error on the `Configurable` decorator.

This is my code:
```typescript
@Configurable()
public constructor(@ConfigParam('app.env') private readonly env: string) { }
```

And this is the error: `TS1206: Decorators are not valid here`.

I managed to make it work with this:
```typescript
private readonly env: string;

public constructor(private readonly config: ConfigService) {
  this.env = config.get('app.env');
}
```
but that defeats completly the purpose of the decorators.

Am I doing something wrong?

**Comment by shekohex** [comment]
Actually you can't :( 
It's kinda of Typescript limition

As docs syes:

> A Class Decorator is declared just before a class declaration. The class decorator is applied to the constructor of the class and can be used to observe, modify, or replace a class definition. A class decorator cannot be used in a declaration file, or in any other ambient context (such as on a declare class).
The expression for the class decorator will be called as a function at runtime, with the constructor of the decorated class as its only argument.
If the class decorator returns a value, it will replace the class declaration with the provided constructor function.

https://www.typescriptlang.org/docs/handbook/decorators.html

So could you please try to add
`@Configurable()` in the class level, not the Constructor, and try again ?

I need to test that too.

**Comment by bashleigh** [comment]
I don't think you can apply a method decorator on the constructor? We could develop a class decorator but this would also defeat the purpose as we'd override the constructor method to inject the ConfigService. Where are you using the configured variable? 

It might be possible to use the static method on the ConfigService within your constructor. 

```ts
export class Test {
  constructor() {
    this.property = ConfigService.get('app.env');
  }
}
```

Else I would use the `Configurable` decorator on the class's methods where you would use the variable.
Or another method would be to use a factory 

```ts
import {Module} from '@nestjs/common';

@Module({
  imports: [ConfigModule],
  providers: [{
    useFactory: (config: ConfigService) => new Test(config.get('app.env')),
    inject: [ConfigService],
})
export class TestModule {}
```
Not really what you want though is it? But doesn't inject into your provider.

**Comment by Syy0n** [comment]
Any updates on this?

**Comment by FahmyChaabane** [comment]
Hello from the future !! 

I'm stuck at this. was there any workaround for this ?
