### ISSUE TITLE
Not possible to use full TypeScript syntax in the config file

### ISSUE THREAD

**Issue by moltar** [nestjs-community/nestjs-config#41]
When I have the following config:

```config/app.ts```
```typescript
interface Config {
  clientId: string
  clientSecret: string
}

const config: Config = {
  clientId: process.env.CLIENT_ID,
  clientSecret: process.env.CLIENT_SECRET,
}

export default config;
```

After `tsc` transpiling, and running (`npm run start:prod`) produces:

```
.../src/config/app.ts:1
(function (exports, require, module, __filename, __dirname) { interface Config {
                                                                        ^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:670:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at configPaths.reduce (.../node_modules/nestjs-config/dist/module/config.service.js:211:28)
```

Which is interesting, as it appears that the code uses `require` and maybe that causes issues?

https://github.com/nestjs-community/nestjs-config/blob/014f8a29bb7f4b1a92911dfec0cdd667a9844b26/src/module/config.service.ts#L250

Thanks!

**Comment by moltar** [comment]
Huh, as soon as I posted, had another sip of coffee and it came to me!

The culprit is in the definition files that are created for the config files. The resulting files are:

```
dist/config/app.js
dist/config/app.d.ts
dist/config/app.js.map
```

And `defaultGlob` is defined like:

```typescript
 protected static defaultGlob: string = 'src/config/**/*.{ts,js}';
```

So, the production run then tries to pick up the definition files.

The easiest fix would probably be to exclude the definition files from the glob.

**Comment by bashleigh** [comment]
I think this might be related to a recent change @kyvour introduced? I believe he added a root to guess/store a application root in order to obtain the path relative to cwd? It's been a while since I've looked at the source myself. I'll have a deeper look soon!

**Comment by moltar** [comment]
The glob pattern I posted above works. I tested it just now. You can add your other bits to it:

```
`${process.cwd()}/src/config/**/!(*.d).{js,ts,json}`
```

**Comment by bashleigh** [comment]
would you like to make a PR for this?

**Comment by moltar** [comment]
I'm confused, though. Is `process.cwd()` and `json` supposed to be there? What shall I base the PR off of? Is there some branch that WIP on this?

**Comment by bashleigh** [comment]
na :) you can fork, call it what you like, PR in and reference this issue. Erm, I'd say defo no to json. process.cwd could be this.root I suppose but can't call that on a property declare I expect? I don't mind doing it, I just might be a week or so

**Comment by bashleigh** [comment]
Think I've solved it? Looks like it was what you said :) quick fix!
