### ISSUE TITLE
How to use config service within app.module.ts

### ISSUE THREAD

**Issue by adetoola** [nestjs-community/nestjs-config#46]
I have the following folder structure (as given in the getting started section of the readme)
```
/src
├── app.module.ts
├── config
│   ├── app.ts
...
```
In my app.module.ts, I have 
```typescript
import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { ConfigModule, ConfigService } from 'nestjs-config';

@Module({
  imports: [ConfigModule.load()],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {
  constructor(private readonly config: ConfigService) {
    this.config = config;
    console.log(config);  // ConfigService { helpers: {} }
    AppModule.host = this.config.get('app.url');
    console.log( 'App URL is',  this.config.get('app.url') ); // App URL is undefined
  }
...
}
```

What could I be doing wrong?

**Comment by nartc** [comment]
By the time the `AppModule Constructor` runs, it hasn't initialized `ConfigModule` via *Dependency Injection* yet. 

Have you tried `OnModuleInit` lifecycle hook?

**Comment by bashleigh** [comment]
I think this is related to #45 where using .load without a path resolves cwd and not src. I haven't really decided what the best fix would be.

**Comment by bashleigh** [comment]
#35

**Comment by adetoola** [comment]
@bashleigh. Yeah, I eventually figured it out after a while. Will you consider updating the `readme` to reflect this. I spent alot of time trying to figure out what I was doing wrong and even went the route suggested by @natrc without knowing this is a bug that has already been reported.

**Comment by bashleigh** [comment]
I think instead I'm going to remove the empty load example and do a complete refactor and clean up for the main service and also see if I can improve the decorator usage. Plus keep this issue open until I've done so.

**Comment by charbel14** [comment]
It will also be good to show how to make use of this in the bootstrap/main.ts itself. Given that access to the port is needed for example.

Ideally, config service should be one of the first things loaded in an app before even the server is started, once loaded it should be available globally always.

Also, it would be nice that if it can easily (read seamlessly) be injected as middleware so it reloads at runtime and only if files changed for perf reasons.

See : [https://github.com/kelseyhightower/envconfig]( Golang Env Config) for some ideas. I have used this go module previously.

**Comment by zMotivat0r** [comment]
@charbel14 my workaround to use it inside `main.ts`:

```ts
import { ConfigService } from 'nestjs-config';
import * as path from 'path';

function getConfig() {
  return (ConfigService as any).loadConfigSync(
    path.join(__dirname, './config/*.{ts,js}'),
  );
}
```

**Comment by mrpharderwijk** [comment]
Any news on this one? Currently my only workaround is defining the service in the constructor and access the env variables by `process.env` directly. This defies to whole purpose of the ConfigService than only exposing the environment variables...
