### ISSUE TITLE
[Best Practice] Boolean Values in Config Files

### ISSUE THREAD

**Issue by johannesschobel** [nestjs-community/nestjs-config#51]
Dear all,

thanks for this wonderful package.
I recently stumbled upon an issue where i would like to get your input on how to deal with this properly (e.g., best practice).

Consider the following config file:
```ts
// config/debug.ts
export default {
  debug_mode: process.env.APP_DEBUG || false,
};
```

Basically, it reads the `.env` file to get the `APP_DEBUG` config value, otherwise it is set to `false`.
Now, if i want to use it like this in a service:

```ts
if (configService.get('debug.debug_mode', false) === true) {
   // do something that needs to be done, if the debug mode is enabled, e.g., extensive logging
}
```
this is never executed, because the value, that is read from the `.env` file is interpreted as `string` (e.g., `typeof configService.get('debug.debug_mode')` is `string` and not `boolean` as one would guess.

How do you deal with boolean values in `.env` files specifically?
For now, the best approach for me is as follows
```ts
// "cast" it as boolean
const enabled = !! configService.get('debug.debug_mode', false);
if (enabled === true) { /* ... */ }
```

What would you suggest?
All the best

**Comment by johannesschobel** [comment]
my initial thought was to make an explicit cast in the `configService.get()` method via an optional param.. 
e.g., 
```ts
const debug = configService.get('debug.debug_mode', false, boolean);
```

so internally the value is directly casted.. What do you think?

**Comment by bashleigh** [comment]
Honestly I think there's lots of ways of doing it. The 2 methods I've consider are 

 1) Validating the env that it is a boolean #33 
 2) Converting the value to a boolean

Both have pros and cons and honestly I think it's a little over the top maybe? Like I said there's nothing wrong with returning a boolean based on a condition like `{ debug_mode: process.env.hasOwnProperty('APP_DEBUG') }`.

It might be worth auto converting `'true'`, `'TRUE'` and `'false'` etc but I feel like it's very specific to this instance.

**Comment by zMotivat0r** [comment]
Hi guys! Let me share my approach if you don't mind :)

```ts
import { get } from 'env-var';

export default {
  version: get('SERVER_VERSION', 'v1').asString(),
  port: get('SERVER_PORT', '3000').asIntPositive(),
};
```
Cheers!

**Comment by johannesschobel** [comment]
@zMotivat0r oh wow, i really like this approach - this is very clean!
Thanks a lot for your input!

**Comment by johannesschobel** [comment]
i just tried the `env-var` approach and it works like a charm! I **really** (!) like it!

**Comment by zeonglow** [comment]
This is worth implementing as a feature as part of the config service IMHO. 

I found the config service a little counter intuitive;

```typescript
   const isDev = configService.getOrThrow<boolean>("app.isDev");
```
Works *for me*  because we have a ConfigFactory called 'app' which returns a boolean for this value.

The issue is when a junior developer does something like this

```typescript
const disableAllAuth = configService.get<boolean>("DISABLE_ALL_AUTH", false ) 
```

which will set disableAllAuth to true if the .env file has  
DISABLE_ALL_AUTH=false
because the string 'false' is truthy

( don't worry,  the real world example I'm basing this on was far less serious than this 😂 )

Building on [johannesschobel](https://github.com/johannesschobel)'s  idea

Something like
```typescript
configService.getBoolean(.. )
```

So we can keep the option for a default parameter might help
