### ISSUE TITLE
Custom env file name

### ISSUE THREAD

**Issue by radziszp** [nestjs-community/nestjs-config#55]
Hello,
as written in  docs: 

> Note: By default the package look for a .env file in the path that you have started your server from. If you want to specify another path for your .env file, use the second parameter of ConfigModule.load().

I'd like to set different .env file for Test module. 
When i'm doing 
```
ConfigModule.load(
  path.resolve(__dirname, 'config/*.{ts,js}'),
    {
      path: 'mypath/.env.test',
    }
)
```
I'm getting 

> error TS2345: Argument of type '{ path: string; }' is not assignable to parameter of type 'ConfigOptions'.

So, how should `options` parameter looks like?

Also is there a possibility, to extend in `.env.test` file values from default `.env` file, so wouldn't i have to duplicate code?

Thanks

**Comment by bashleigh** [comment]
I think I saw your question on stackoverflow ;) 

That should be the correct behaviour. I'll add a test for this scenario and fix this issue

**Comment by radziszp** [comment]
Wasn't me, but glad i'm not the only one who couldn't fix it by himself :)
I'm using `v 1.2.9`
Thanks! I'm looking forward for updates

**Comment by bashleigh** [comment]
so, update on this. There was  a PR made recently where I was asked to change `export ConfigOptions = {...} & EnvOptions` to `export interface ConfigOptions extends EnvOptions {...}`. Changing it back to the latter seems to work, however I don't understand why the former doesn't work? https://github.com/nestjs-community/nestjs-config/pull/48/commits/aab42650a71d5ff9b9cb0e4b7cec57b27119f1ed#diff-11f5a2a5cc6df739d69a8a8c4f8ecffbR23

**Comment by bashleigh** [comment]
This should now be resolved in the next release :)

**Comment by radziszp** [comment]
:+1: Thanks!

**Comment by Diluka** [comment]
What shall I pass the `path` value?
```ts
// src/bootstrap.module.ts
ConfigModule.resolveSrcPath(__dirname).load('config/**/!(*.d).{ts,js}', { path: '.env.test' }),
```
```env
# .env.test
DEMO=test
```

It doesn't load the file `.env.test` instead it loading `.env`. Seems the `path` options has been ignored.

**Comment by bashleigh** [comment]
@Diluka I think you need to add the full path. Try that and let me know how it goes. I shall have a think about whether to add a method to add the cwd path by default
