### ISSUE TITLE
Document config.src()

### ISSUE THREAD

**Issue by mchelen** [nestjs-community/nestjs-config#61]
There is a `config.src()` function used in an [example](https://github.com/nestjs-community/nestjs-config/blob/master/examples/basic/user.controller.ts#L24) but it is not documented in the [README](https://github.com/nestjs-community/nestjs-config#configservice-api)

**Comment by bashleigh** [comment]
Honestly I'm thinking of possibly changing/removing it. At the time I was aiming for a path to `src` for my view/template folder but I think it the root method makes this obsolete. The name is also confusing as in production the directory will change to `dist` or there alike. 
There's also this to consider #54 so I'm not really sure what to do with the method at this stage. But you're right it should be documented and backwards compatible just incase. so 

```ts
public static root(): string {
  const srcPath = this.srcPath || path.resolve(process.cwd(), dir);
  return path.resolve(srcPath, dir);
}

public static src(): string {
  return this.root();
}
```

Same goes for `resolveSrcPath` which I mentioned here #53.

**Comment by bashleigh** [comment]
if you're interested. I decided it's best to remove src. However I've kept the method for backwards compatibility. As of #73 it's best to use `root()` in order to use  the `src` functionality. Hopefully this change will reduce human error :)
