### ISSUE TITLE
@types/dotenv out of date

### ISSUE THREAD

**Issue by Diluka** [nestjs-community/nestjs-config#63]
https://github.com/nestjs-community/nestjs-config/blob/1b494d2a0fa9005ad7fe153805ab8d41c3feff3c/package.json#L52

https://github.com/nestjs-community/nestjs-config/blob/1b494d2a0fa9005ad7fe153805ab8d41c3feff3c/package.json#L41

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/028e63335139a3a0639b538a6aab9fe3fb7cfa38/types/dotenv/index.d.ts#L34-L49

Error:(1, 10) TS2305: Module '"@types/dotenv"' has no exported member 'DotenvOptions'.

**Comment by bashleigh** [comment]
That's weird. You have excluded the node_modules folder in your tsconfig?

**Comment by dhaspden** [comment]
Having this issue as well, I have fixed for now by downgrading `@types/dotenv` to `4.0.3`.

**Comment by bashleigh** [comment]
Will be fixed in next release 👍
