### ISSUE TITLE
crashed when value is null

### ISSUE THREAD

**Issue by Diluka** [nestjs-community/nestjs-config#64]
https://github.com/nestjs-community/nestjs-config/blob/2b881cedbbe6bb556d762c52abe66adb5d62da5d/src/module/config.service.ts#L283

because `typeof null === 'object'`

**Comment by bashleigh** [comment]
@Diluka Could you provide an example to replicate?

**Comment by bashleigh** [comment]
I've made a quick fix for this #71 . Looking at going forward with removing unwanted helper methods being created #72

**Comment by bashleigh** [comment]
will be fixed in next release 👍
