### ISSUE TITLE
WARNING!! The "modules" key in the @Module() decorator is deprecated and will be removed within next major release. Use the "imports" key instead.

### ISSUE THREAD

**Issue by ruscon** [nestjs-community/nestjs-config#79]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**nestjs-config version** 
@latest

**@nestjs/common+core or other package versions**
 - @nestjs/common: 5.7.3
 - @nestjs/core: 5.7.3

#### Excepted behavior 
No warnings

#### Actual behavior or outcome (for issue)
https://github.com/nestjs/nest/blob/master/packages/common/decorators/modules/module.decorator.ts#L39
```
WARNING!!
The "modules" key in the @Module() decorator is deprecated and will be removed within next major release. Use the "imports" key instead.
```

**Comment by johannesschobel** [comment]
this is related to the upcoming `nestjs 6.0.0` version..
See the "new" decorator here (currently rc1 state):
https://github.com/nestjs/nest/blob/00ddc0aeeb2b7c75203fa53826b1e3c86f3c0f00/packages/common/decorators/modules/module.decorator.ts#L5-L10

However, the official docs for the current (5.x) version of nestjs ( https://docs.nestjs.com/modules ) **does not** indicate to use the `modules` key.. it suggest to use `imports`

All the best

**Comment by bashleigh** [comment]
This doesn't appear to be an issue eith nestjs-config. Try searching your code base for where you might've used the modules key. 

I'm going to close this however if you find it is the nestjs-config modules please provide code examples and I'll look into it :)
